name: Backend CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install packages
      run: dotnet restore DotStatistics.sln
    - name: Build
      run: dotnet build DotStatistics.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test DotStatistics.sln --configuration Release --no-restore
